# Generated by Django 3.1.4 on 2021-01-12 09:08

from django.db import migrations, models
import mngs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, help_text='状态', max_length=150, null=True)),
                ('client_name', models.CharField(blank=True, help_text='客户/代理/销售名称', max_length=150, null=True)),
                ('client_no', models.CharField(blank=True, help_text='客户编号', max_length=150, null=True)),
                ('knoin_no', models.CharField(blank=True, help_text='诺因编号', max_length=150, null=True)),
                ('sample_type', models.CharField(blank=True, help_text='样本类型', max_length=150, null=True)),
                ('detect_type', models.CharField(blank=True, help_text='送检项目', max_length=150, null=True)),
                ('patient_name', models.CharField(blank=True, help_text='患者姓名', max_length=150, null=True)),
                ('gender', models.CharField(blank=True, help_text='性别', max_length=150, null=True)),
                ('age', models.CharField(blank=True, help_text='年龄', max_length=150, null=True)),
                ('hospital', models.CharField(blank=True, help_text='医院', max_length=150, null=True)),
                ('department', models.CharField(blank=True, help_text='科室', max_length=150, null=True)),
                ('dockor_name', models.CharField(blank=True, help_text='医生', max_length=150, null=True)),
                ('report_format', models.CharField(blank=True, help_text='报告版式', max_length=150, null=True)),
                ('sampling_date', models.CharField(blank=True, help_text='采样日期', max_length=150, null=True)),
                ('diagnosis', models.CharField(blank=True, help_text='临床诊断', max_length=150, null=True)),
                ('pathogen', models.CharField(blank=True, help_text='关注病原', max_length=150, null=True)),
                ('WBC', models.CharField(blank=True, help_text='WBC', max_length=150, null=True)),
                ('CRP', models.CharField(blank=True, help_text='CRP', max_length=150, null=True)),
                ('lymphocytes', models.CharField(blank=True, help_text='淋巴细胞', max_length=150, null=True)),
                ('PCT', models.CharField(blank=True, help_text='PCT', max_length=150, null=True)),
                ('neutr_granule', models.CharField(blank=True, help_text='中性粒细胞', max_length=150, null=True)),
                ('detect_result', models.CharField(blank=True, help_text='培养鉴定结果', max_length=150, null=True)),
                ('clinical_manifestations', models.CharField(blank=True, help_text='临床表现', max_length=150, null=True)),
                ('medication', models.CharField(blank=True, help_text='用药情况', max_length=150, null=True)),
                ('collect_date', models.CharField(blank=True, help_text='收样日期', max_length=150, null=True)),
                ('report_time', models.CharField(blank=True, help_text='报告日期', max_length=150, null=True)),
                ('bio_info', models.CharField(blank=True, help_text='生物信息补充', max_length=150, null=True)),
                ('detect_status', models.CharField(blank=True, help_text='项目状态', max_length=150, null=True)),
                ('sample_size', models.CharField(blank=True, help_text='样本量', max_length=150, null=True)),
                ('analys_file_path', models.CharField(blank=True, help_text='分析文件目录', max_length=150, null=True)),
                ('sample_file_path', models.CharField(blank=True, help_text='样本文件目录', max_length=150, null=True)),
                ('analys_report', models.FileField(blank=True, help_text='分析结果报告', null=True, upload_to=mngs.models.upload_to_result)),
                ('qc', models.FileField(blank=True, help_text='质控结果1', null=True, upload_to=mngs.models.upload_to_result)),
                ('kraken2_qc', models.FileField(blank=True, help_text='质控结果2', null=True, upload_to=mngs.models.upload_to_result)),
                ('qc_image', models.FileField(blank=True, help_text='质控图片', null=True, upload_to=mngs.models.upload_to_result)),
                ('main_sh', models.FileField(blank=True, help_text='运行脚本', null=True, upload_to=mngs.models.upload_to_config)),
                ('sam_ini', models.FileField(blank=True, help_text='sam.ini', null=True, upload_to=mngs.models.upload_to_config)),
                ('sys_ini', models.FileField(blank=True, help_text='sys.ini', null=True, upload_to=mngs.models.upload_to_config)),
            ],
        ),
    ]
