# Generated by Django 3.1.3 on 2021-01-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='状态', max_length=150)),
                ('client_name', models.CharField(help_text='客户/代理/销售名称', max_length=150)),
                ('client_no', models.CharField(help_text='客户编号', max_length=150)),
                ('knoin_no', models.CharField(help_text='诺因编号', max_length=150)),
            ],
        ),
    ]
