# Generated by Django 3.1.3 on 2021-01-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, help_text='客户/代理/销售名称', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_no',
            field=models.CharField(blank=True, help_text='客户编号', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='knoin_no',
            field=models.CharField(blank=True, help_text='诺因编号', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, help_text='状态', max_length=150, null=True),
        ),
    ]
