# Generated by Django 3.1.3 on 2021-01-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngs', '0002_auto_20210109_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='CRP',
            field=models.CharField(blank=True, help_text='CRP', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='PCT',
            field=models.CharField(blank=True, help_text='PCT', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='WBC',
            field=models.CharField(blank=True, help_text='WBC', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='age',
            field=models.CharField(blank=True, help_text='年龄', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='bio_info',
            field=models.CharField(blank=True, help_text='生物信息补充', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='clinical_manifestations',
            field=models.CharField(blank=True, help_text='临床表现', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='collect_date',
            field=models.CharField(blank=True, help_text='收样日期', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, help_text='科室', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='detect_result',
            field=models.CharField(blank=True, help_text='培养鉴定结果', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='detect_status',
            field=models.CharField(blank=True, help_text='项目状态', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='detect_type',
            field=models.CharField(blank=True, help_text='送检项目', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='diagnosis',
            field=models.CharField(blank=True, help_text='临床诊断', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dockor_name',
            field=models.CharField(blank=True, help_text='医生', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gender',
            field=models.CharField(blank=True, help_text='性别', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hospital',
            field=models.CharField(blank=True, help_text='医院', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lymphocytes',
            field=models.CharField(blank=True, help_text='淋巴细胞', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='medication',
            field=models.CharField(blank=True, help_text='用药情况', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='neutr_granule',
            field=models.CharField(blank=True, help_text='中性粒细胞', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pathogen',
            field=models.CharField(blank=True, help_text='关注病原', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='patient_name',
            field=models.CharField(blank=True, help_text='患者姓名', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='report_format',
            field=models.CharField(blank=True, help_text='报告版式', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='report_time',
            field=models.CharField(blank=True, help_text='报告日期', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sample_size',
            field=models.CharField(blank=True, help_text='样本量', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sample_type',
            field=models.CharField(blank=True, help_text='样本类型', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sampling_date',
            field=models.CharField(blank=True, help_text='采样日期', max_length=150, null=True),
        ),
    ]
