# Generated by Django 3.1.3 on 2021-01-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngs', '0003_auto_20210114_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='项目批次', max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='collection_id',
            field=models.CharField(blank=True, help_text='批次id', max_length=150, null=True),
        ),
    ]
