# Generated by Django 3.1.3 on 2021-01-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngs', '0003_auto_20210109_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analys_file_path',
            field=models.CharField(blank=True, help_text='分析文件目录', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sample_file_path',
            field=models.CharField(blank=True, help_text='样本文件目录', max_length=150, null=True),
        ),
    ]
