# Generated by Django 3.1.3 on 2021-01-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngs', '0004_auto_20210118_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='ctrl_file_name',
            field=models.CharField(blank=True, help_text='参考文件名称', max_length=150, null=True),
        ),
    ]
