# Generated by Django 3.1.4 on 2021-01-19 04:26

from django.db import migrations, models
import mngs.models


class Migration(migrations.Migration):

    dependencies = [
        ('mngs', '0005_collection_ctrl_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_sh',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sam_ini',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sys_ini',
        ),
        migrations.AddField(
            model_name='collection',
            name='main_sh',
            field=models.FileField(blank=True, help_text='运行脚本', null=True, upload_to=mngs.models.upload_to_config),
        ),
        migrations.AddField(
            model_name='collection',
            name='sam_ini',
            field=models.FileField(blank=True, help_text='sam.ini', null=True, upload_to=mngs.models.upload_to_config),
        ),
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(blank=True, help_text='状态', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='sys_ini',
            field=models.FileField(blank=True, help_text='sys.ini', null=True, upload_to=mngs.models.upload_to_config),
        ),
    ]
