# Generated by Django 3.1.4 on 2021-01-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngs', '0006_auto_20210119_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='ctrl_file_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='analys_file_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sample_file_name',
        ),
        migrations.AddField(
            model_name='collection',
            name='ctrl_file_path',
            field=models.CharField(blank=True, help_text='参考文件绝对路径', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='analys_file_path',
            field=models.CharField(blank=True, help_text='分析文件绝对路径', max_length=150, null=True),
        ),
    ]
