# Generated by Django 3.1.4 on 2021-01-28 06:04

from django.db import migrations, models
import mngs.models


class Migration(migrations.Migration):

    dependencies = [
        ('mngs', '0007_auto_20210119_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='results_zip_file',
            field=models.FileField(blank=True, help_text='分析结果zip文件', null=True, upload_to=mngs.models.upload_to_config),
        ),
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.CharField(blank=True, default='已创建', help_text='状态', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, default='已创建', help_text='状态', max_length=150, null=True),
        ),
    ]
