# Generated by Django 3.1.4 on 2021-02-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mngs', '0009_auto_20210128_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='finished_sections',
            field=models.CharField(blank=True, help_text='已经分析完的模块', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='sections',
            field=models.CharField(blank=True, help_text='所有模块', max_length=150, null=True),
        ),
    ]
