# Generated by Django 3.1.4 on 2021-01-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileManager',
        ),
    ]
